dist: xenial
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=check-py27
    - python: 3.6
      env: TOXENV=flake8,pylint,check-py36

addons:
  apt:
    packages:
    - libgirepository1.0-dev

install:
  - pip install tox

script:
  - tox

after_success:
  - tox -e coveralls
